# Generated by Django 5.1.4 on 2024-12-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='billing_address',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
